---
- name: Oracle JDK | Add webupd8 repository apt-key
  apt_key:
    url: "http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xC2518248EEA14886"
    state: present

- name: Oracle JDK | Add webupd8 repository
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main'
    state: present
- name: Oracle JDK | Accept the oracle license
  shell: "echo {{item}} shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections"
  with_items:
    - oracle-java{{java_version}}-installer

- name: Oracle JDK | Install JDK package
  apt:
    name: "oracle-java{{java_version}}-installer"
    state: present
    update_cache: yes

- name: Oracle JDK | Set the default Java version
  apt:
    name: "oracle-java{{java_version}}-set-default"
    state: present
    update_cache: yes